<?php
/**
 * @file
 * Module developed to meet unique software use case requirements as defined
 * by New Era Technology Inc. Custom module development was necessary as no
 * existing modules match required use cases.       
 */
/**
 * Implements hook_help().
 */
function tssp_help($path, $arg){
	switch($path) {
		case 'admin/help#tssp':{
			$ret_val = '<h3>' . t('About') . '</h3>';
			$ret_val .= '<p>' . t('Module created to meet specific use cases in the development of TSSP2016. <br />Module Author: Michael A. Stratton.') . '</p><br />';
                        $ret_val .= '<hr>';
                        $ret_val .= '<h4>' . t('Use Case I: Aircraft Issues Menu') . '</h4>';
                        $ret_val .= '<p>' . t('Hook implementations for user-created content types <br />'
                                            . 'https://api.drupal.org/api/drupal/modules!node!node.module/group/node_content/7.x.') . '</p>';
                        $ret_val .= '<p>' . t('two drupal content types. <br />
										content_type1 = aircraft <br />
										content_type2 = aircraft_issues') . '</p>';
                        $ret_val .= '<p>' . t('aircraft has the fields(not complete list): <br />
										tail_number(text) <br />
										active(boolean)') . '</p>';
                        $ret_val .= '<p>' . t('aircraft_issues has the fields:<br />
										issue_name(text)<br />
										aircraft_tail_number(entity_reference to aircraft table) <br />
										description(text_area)') . '</p>';
						$ret_val .= '<p>' . t('show a drop down menu that lists all aircrafts from the aircraft_issues table. <br />
												Only aircraft that are listed as "active(boolean field)" in the "aircrafts" table should be displayed in the menu.<br />
												PSEUDO CODE:<br />
												SELECT aircrafts FROM aircraft_issues<br />
												if (TABLE == aircrafts && active == false) {<br />
													do not display taxi in menu<br />
													}<br />
													else { display taxi in menu }') . '</p>';
						$ret_val .= '<p>' . t('If the user selects the an aircraft from the drop down menu, all known issues for that particular aircraft will be listed in a table format.<br />
												PSEUDO CODE:<br />
												SELECT issue_name, description FROM aircraft_issues WHERE aircraft_name = menu_selection') . '</p>';
						$ret_val .= '<p>' . t('UI: Drop down menu only') . '</p>';
                        return $ret_val;
			break;
		}
	}
}

/**
 * Implements hook_menu().
 */
function form_example_menu() {
  $items = array();

  $items['examples/form-example'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Example Form', //page title
    'description' => 'A form to mess around with.',
    'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => array('form_example_form'), //put the name of the form here
    'access callback' => TRUE
  );

  return $items;
}

/**
 * Implements hook_form().
 */
function form_example_form($form, &$form_state) {
  
 $form['price'] = array(
    '#type' => 'textfield', //you can find a list of available types in the form api
    '#title' => 'What is Your Price?',
    '#size' => 10,
    '#maxlength' => 10,
    '#required' => TRUE, //make this field required 
  );

  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Click Here!'),
  );
  
  return $form;
}

function form_example_form_validate($form, &$form_state) {
}

function form_example_form_submit($form, &$form_state) {
}