<?php
/**
 * @file
 * Module developed to meet unique software use case requirements as defined
 * by New Era Technology Inc. Custom module development was necessary as no
 * existing modules match required use cases.       
 */
/**
 * Implements hook_help().
 */
function tssp_help($path, $arg){
	switch($path) {
		case 'admin/help#tssp':{
			$ret_val = '<h3>' . t('About') . '</h3>';
			$ret_val .= '<p>' . t('Module created to meet specific use cases in the development of TSSP2016.') . '</p>';
			$ret_val .= '<p>' . t('Module Author: Michael A. Stratton.') . '</p>';
                        $ret_val .= '<h4>' . t('Use Case I: Aircraft Issues Menu') . '</h4>';
                        $ret_val .= '<p>' . t('Hook implementations for user-created content types <br />'
                                            . 'https://api.drupal.org/api/drupal/modules!node!node.module/group/node_content/7.x.') . '</p>';
                        return $ret_val;
			break;
		}
	}
}